"use client";
import Link from "next/link";
import { signIn } from "next-auth/react";
import { useRouter, useSearchParams } from "next/navigation";
import { ClipboardEvent, FormEvent, KeyboardEvent, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PasswordInput } from "@/components/ui/password-input";
const inputClass="border border-white/10 bg-white/[.06] text-white placeholder:text-white/35 focus-visible:border-[#22c55e] focus-visible:ring-[#22c55e]/20";
const strengthLabels=["Too weak","Weak","Fair","Strong","Very strong"];
const strengthColors=["bg-red-500","bg-orange-500","bg-yellow-400","bg-lime-400","bg-[#22c55e]"];
function passwordStrength(password:string){if(!password)return 0;return Math.min(4,[password.length>=8,/[a-z]/.test(password)&&/[A-Z]/.test(password),/\d/.test(password),/[^A-Za-z0-9]/.test(password)].filter(Boolean).length)}
function VerificationCodeInput({value,onChange}:{value:string;onChange:(value:string)=>void}){
const refs=useRef<Array<HTMLInputElement|null>>([]),digits=Array.from({length:6},(_,index)=>value[index]||"");
const focus=(index:number)=>refs.current[Math.max(0,Math.min(5,index))]?.focus();
const setDigit=(index:number,next:string)=>{const digit=next.replace(/\D/g,"").slice(-1),updated=[...digits];updated[index]=digit;onChange(updated.join(""));if(digit&&index<5)focus(index+1)};
const keyDown=(event:KeyboardEvent<HTMLInputElement>,index:number)=>{if(event.key==="Backspace"&&!digits[index]&&index>0){event.preventDefault();const updated=[...digits];updated[index-1]="";onChange(updated.join(""));focus(index-1)}else if(event.key==="ArrowLeft"){event.preventDefault();focus(index-1)}else if(event.key==="ArrowRight"){event.preventDefault();focus(index+1)}};
const paste=(event:ClipboardEvent<HTMLDivElement>)=>{const pasted=event.clipboardData.getData("text").replace(/\D/g,"").slice(0,6);if(!pasted)return;event.preventDefault();onChange(pasted);focus(Math.min(pasted.length,5))};
return <div role="group" aria-label="6-digit verification code" onPaste={paste} className="flex justify-center gap-2 sm:gap-3">{digits.map((digit,index)=><input key={index} ref={element=>{refs.current[index]=element}} required aria-label={`Digit ${index+1}`} autoFocus={index===0} autoComplete={index===0?"one-time-code":"off"} inputMode="numeric" pattern="[0-9]" maxLength={1} value={digit} onChange={event=>setDigit(index,event.target.value)} onKeyDown={event=>keyDown(event,index)} onFocus={event=>event.currentTarget.select()} className="h-14 w-11 rounded-xl border border-white/15 bg-white/[.06] text-center text-2xl font-bold text-white outline-none transition focus:border-[#22c55e] focus:ring-4 focus:ring-[#22c55e]/15 sm:h-16 sm:w-12"/>)}</div>}
export default function SignUpForm(){const router=useRouter(),params=useSearchParams(),gymId=params?.get("gymId")||"",invite=params?.get("invite")||"";const[step,setStep]=useState<"account"|"code">("account"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
async function createAccount(event:FormEvent){event.preventDefault();setBusy(true);setError("");const response=await fetch("/api/user",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,gymId:gymId||null,visitorId:localStorage.getItem("fittingin_visitor_id"),visitId:sessionStorage.getItem("fittingin_visit_id"),clickedAt:localStorage.getItem("fittingin_day_pass_clicked_at")})});const result=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(result.message||"Unable to create your account.");return}setStep("code");setMessage("We sent a 6-digit verification code to your email.")}
async function verifyCode(event:FormEvent){event.preventDefault();const externalTab=gymId?window.open("about:blank","_blank"):null;if(externalTab)externalTab.opener=null;setBusy(true);setError("");const response=await fetch("/api/auth/verify-email",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,code})});const result=await response.json().catch(()=>({}));if(!response.ok){externalTab?.close();setBusy(false);setError(result.error||"That code is invalid or expired.");return}const login=await signIn("credentials",{email,password,redirect:false});setBusy(false);if(login?.error){externalTab?.close();setError("Email verified. Please log in to continue.");return}localStorage.removeItem("fittingin_day_pass_clicked_at");if(invite){externalTab?.close();router.push(`/gym-invite/${encodeURIComponent(invite)}?claim=1`);router.refresh();return}if(gymId){localStorage.setItem("fittingin_pending_day_pass_confirmation",JSON.stringify({gymId,openedAt:Date.now()}));const destinationPath=`/day-pass/${encodeURIComponent(gymId)}`;if(externalTab){externalTab.location.href=`${window.location.origin}${destinationPath}`;externalTab.focus()}else window.open(destinationPath,"_blank","noopener,noreferrer");window.location.assign("/");return}router.push("/");router.refresh()}
async function resend(){setBusy(true);setError("");const response=await fetch("/api/auth/verify-email/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});setBusy(false);setMessage(response.ok?"A new 6-digit code was sent.":"Unable to resend the code.")}
const strength=passwordStrength(password),loginCallback=invite?`/gym-invite/${invite}?claim=1`:gymId?`/day-pass/${gymId}`:"";return <div className="text-white"><h1 className={`${step==="account"?"mb-6":"mb-2"} text-center text-3xl font-semibold`}>{step==="account"?"Sign up":"Verify your email"}</h1>{step==="code"&&<p className="mb-5 text-center text-sm text-white/50">Enter the code sent to {email}.</p>}{error&&<p className="mb-4 rounded-xl border border-red-500/35 bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}{message&&step==="code"&&<p className="mb-4 rounded-xl border border-[#22c55e]/35 bg-[#22c55e]/10 p-3 text-sm text-[#86efac]">{message}</p>}{step==="account"?<form onSubmit={createAccount} className="space-y-4"><label className="block text-sm font-medium">Email<Input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" className={`mt-2 ${inputClass}`}/></label><label className="block text-sm font-medium">Password<PasswordInput required minLength={8} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters" className={`mt-2 ${inputClass}`}/><div className="mt-2" aria-live="polite"><div className="flex gap-1.5">{[1,2,3,4].map(level=><span key={level} className={`h-1.5 flex-1 rounded-full transition-colors ${password&&strength>=level?strengthColors[strength]:"bg-white/10"}`}/>)}</div><div className="mt-1.5 flex justify-between text-xs"><span className={password?"text-white/60":"text-white/35"}>{password?strengthLabels[strength]:"Password strength"}</span><span className="text-white/35">8+ characters</span></div></div></label><Button disabled={busy} className="w-full bg-[#22c55e] font-bold text-black hover:bg-[#19a94e]">{busy?"Sending code…":"Continue"}</Button></form>:<form onSubmit={verifyCode} className="space-y-4"><div><p className="mb-3 text-center text-sm font-medium">Enter 6-digit authentication code</p><VerificationCodeInput value={code} onChange={setCode}/></div><Button disabled={busy||code.length!==6} className="w-full bg-[#22c55e] font-bold text-black hover:bg-[#19a94e]">{busy?"Verifying…":"Verify and continue"}</Button><button type="button" disabled={busy} onClick={resend} className="w-full text-sm font-semibold text-[#22c55e] hover:underline">Send a new code</button></form>}<p className="mt-5 text-center text-sm text-white/45">Already have an account? <Link className="font-semibold text-[#22c55e] hover:underline" href={loginCallback?`/log-in?callbackUrl=${encodeURIComponent(loginCallback)}`:"/log-in"}>Log in</Link></p></div>}
