"use client";
import Link from "next/link";
import { signIn } from "next-auth/react";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PasswordInput } from "@/components/ui/password-input";
const inputClass="border border-white/10 bg-white/[.06] text-white placeholder:text-white/35 focus-visible:border-[#22c55e] focus-visible:ring-[#22c55e]/20";
const strengthLabels=["Too weak","Weak","Fair","Strong","Very strong"];
const strengthColors=["bg-red-500","bg-orange-500","bg-yellow-400","bg-lime-400","bg-[#22c55e]"];
function passwordStrength(password:string){if(!password)return 0;return Math.min(4,[password.length>=8,/[a-z]/.test(password)&&/[A-Z]/.test(password),/\d/.test(password),/[^A-Za-z0-9]/.test(password)].filter(Boolean).length)}
export default function SignUpForm(){const router=useRouter(),params=useSearchParams(),gymId=params?.get("gymId")||"";const[step,setStep]=useState<"account"|"code">("account"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
async function createAccount(event:FormEvent){event.preventDefault();setBusy(true);setError("");const response=await fetch("/api/user",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,gymId:gymId||null,visitorId:localStorage.getItem("fittingin_visitor_id"),visitId:sessionStorage.getItem("fittingin_visit_id"),clickedAt:localStorage.getItem("fittingin_day_pass_clicked_at")})});const result=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setError(result.message||"Unable to create your account.");return}setStep("code");setMessage("We sent a 6-digit verification code to your email.")}
async function verifyCode(event:FormEvent){event.preventDefault();setBusy(true);setError("");const response=await fetch("/api/auth/verify-email",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,code})});const result=await response.json().catch(()=>({}));if(!response.ok){setBusy(false);setError(result.error||"That code is invalid or expired.");return}const login=await signIn("credentials",{email,password,redirect:false});setBusy(false);if(login?.error){setError("Email verified. Please log in to continue.");return}localStorage.removeItem("fittingin_day_pass_clicked_at");router.push(gymId?`/day-pass/${encodeURIComponent(gymId)}`:"/");router.refresh()}
async function resend(){setBusy(true);setError("");const response=await fetch("/api/auth/verify-email/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});setBusy(false);setMessage(response.ok?"A new 6-digit code was sent.":"Unable to resend the code.")}
const strength=passwordStrength(password);return <div className="text-white"><h1 className={`${step==="account"?"mb-6":"mb-2"} text-center text-3xl font-semibold`}>{step==="account"?"Sign up":"Verify your email"}</h1>{step==="code"&&<p className="mb-5 text-center text-sm text-white/50">Enter the code sent to {email}.</p>}{error&&<p className="mb-4 rounded-xl border border-red-500/35 bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}{message&&step==="code"&&<p className="mb-4 rounded-xl border border-[#22c55e]/35 bg-[#22c55e]/10 p-3 text-sm text-[#86efac]">{message}</p>}{step==="account"?<form onSubmit={createAccount} className="space-y-4"><label className="block text-sm font-medium">Email<Input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" className={`mt-2 ${inputClass}`}/></label><label className="block text-sm font-medium">Password<PasswordInput required minLength={8} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters" className={`mt-2 ${inputClass}`}/><div className="mt-2" aria-live="polite"><div className="flex gap-1.5">{[1,2,3,4].map(level=><span key={level} className={`h-1.5 flex-1 rounded-full transition-colors ${password&&strength>=level?strengthColors[strength]:"bg-white/10"}`}/>)}</div><div className="mt-1.5 flex justify-between text-xs"><span className={password?"text-white/60":"text-white/35"}>{password?strengthLabels[strength]:"Password strength"}</span><span className="text-white/35">8+ characters</span></div></div></label><Button disabled={busy} className="w-full bg-[#22c55e] font-bold text-black hover:bg-[#19a94e]">{busy?"Sending code…":"Continue"}</Button></form>:<form onSubmit={verifyCode} className="space-y-4"><label className="block text-sm font-medium">6-digit code<Input required autoFocus inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="000000" className={`mt-2 text-center text-2xl tracking-[.35em] ${inputClass}`}/></label><Button disabled={busy||code.length!==6} className="w-full bg-[#22c55e] font-bold text-black hover:bg-[#19a94e]">{busy?"Verifying…":"Verify and continue"}</Button><button type="button" disabled={busy} onClick={resend} className="w-full text-sm font-semibold text-[#22c55e] hover:underline">Send a new code</button></form>}<p className="mt-5 text-center text-sm text-white/45">Already have an account? <Link className="font-semibold text-[#22c55e] hover:underline" href={gymId?`/log-in?callbackUrl=${encodeURIComponent(`/day-pass/${gymId}`)}`:"/log-in"}>Log in</Link></p></div>}
