"use client";

import { Plus, Trash2 } from "lucide-react";
import { BILLING_FREQUENCIES, MembershipOption, emptyMembershipOption, effectiveMonthlyPrice } from "@/lib/memberships";
import CurrencyInput from "@/components/CurrencyInput";

const input = "mt-1 w-full rounded-xl border border-zinc-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-[#22c55e] dark:border-white/10 dark:bg-black/20";
const label = "block text-sm font-medium text-zinc-700 dark:text-zinc-200";

export default function MembershipOptionsEditor({ options, availableAmenities, onChange, showErrors }: { options: MembershipOption[]; availableAmenities: string[]; onChange: (options: MembershipOption[]) => void; showErrors: boolean }) {
  const update = (index: number, values: Partial<MembershipOption>) => onChange(options.map((option, itemIndex) => itemIndex === index ? { ...option, ...values } : option));
  const fieldClass = (invalid: boolean) => `${input} ${showErrors && invalid ? "!border-red-500" : ""}`;
  return <div className="space-y-4">
    {options.map((option, index) => <article key={option.id} className="rounded-2xl border border-zinc-200 bg-zinc-50/70 p-4 dark:border-white/10 dark:bg-black/20">
      <div className="mb-4 flex items-center justify-between gap-3"><div><h3 className="font-black">Membership option {index + 1}</h3><p className="text-xs text-zinc-500">Average monthly price: ${effectiveMonthlyPrice(option).toFixed(2)}</p></div>{options.length>1&&<button type="button" onClick={() => onChange(options.filter((_, itemIndex) => itemIndex !== index))} className="rounded-full border border-red-300 p-2 text-red-500 transition hover:border-red-400 hover:bg-red-50 dark:border-red-400/40 dark:hover:bg-red-500/10" aria-label={`Remove membership option ${index + 1}`}><Trash2 size={16}/></button>}</div>
      <div className="grid gap-3 sm:grid-cols-2">
        <label className={label}>Option name<input className={fieldClass(!option.name)} value={option.name} onChange={event => update(index, { name: event.target.value })} placeholder="Standard Membership" /></label>
        <label className={label}>Price<CurrencyInput label={`${option.name||`Membership option ${index+1}`} price`} className={fieldClass(!Number.isFinite(option.price)||option.price<=0)} value={option.price} onChange={price=>update(index,{price})}/></label>
        <label className={label}>Billing frequency<select className={input} value={option.billingFrequency} onChange={event => update(index, { billingFrequency: event.target.value as MembershipOption["billingFrequency"] })}>{BILLING_FREQUENCIES.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select>{option.billingFrequency==="custom"&&<span className="mt-2 grid grid-cols-2 gap-2"><input aria-label="Custom billing interval" type="number" min="1" step="1" className={fieldClass(option.billingInterval<1)} value={option.billingInterval} onChange={event=>update(index,{billingInterval:Number(event.target.value)})}/><select aria-label="Custom billing interval unit" className={input} value={option.billingIntervalUnit} onChange={event=>update(index,{billingIntervalUnit:event.target.value as MembershipOption["billingIntervalUnit"]})}><option value="days">Days</option><option value="weeks">Weeks</option><option value="months">Months</option></select></span>}</label>
        <label className={label}>Contract length<select className={input} value={option.contractLengthUnit==="months"&&[1,3,6,12,24].includes(option.contractLength)?String(option.contractLength):"other"} onChange={event => update(index, event.target.value==="other"?{contractLength:2,contractLengthUnit:"months"}:{contractLength:Number(event.target.value),contractLengthUnit:"months"})}><option value="1">Month-to-month</option><option value="3">3 months</option><option value="6">6 months</option><option value="12">12 months</option><option value="24">24 months</option><option value="other">Other</option></select>{!(option.contractLengthUnit==="months"&&[1,3,6,12,24].includes(option.contractLength))&&<span className="mt-2 grid grid-cols-2 gap-2"><input aria-label="Custom contract length" type="number" min="1" step="1" className={fieldClass(option.contractLength<1)} value={option.contractLength} onChange={event=>update(index,{contractLength:Number(event.target.value)})}/><select aria-label="Custom contract length unit" className={input} value={option.contractLengthUnit} onChange={event=>update(index,{contractLengthUnit:event.target.value as MembershipOption["contractLengthUnit"]})}><option value="days">Days</option><option value="weeks">Weeks</option><option value="months">Months</option><option value="years">Years</option></select></span>}</label>
        <label className={label}>Enrollment/initiation fee<CurrencyInput label={`${option.name||`Membership option ${index+1}`} enrollment or initiation fee`} className={input} value={option.enrollmentFee} onChange={enrollmentFee=>update(index,{enrollmentFee})}/></label>
        <label className={label}>Annual fee<CurrencyInput label={`${option.name||`Membership option ${index+1}`} annual fee`} className={input} value={option.annualFee} onChange={annualFee=>update(index,{annualFee})}/></label>
        <label className={label}>Additional fees<CurrencyInput label={`${option.name||`Membership option ${index+1}`} additional fees`} className={input} value={option.additionalFees} onChange={additionalFees=>update(index,{additionalFees})}/></label>
        <label className={label}>Additional fee details <span className="text-xs font-normal text-zinc-400">Optional</span><input className={input} value={option.additionalFeesDetails} onChange={event => update(index, { additionalFeesDetails: event.target.value })} placeholder="Key fee, maintenance fee, etc." /></label>
        <fieldset className="sm:col-span-2"><legend className={label}>What&apos;s included (access)</legend>{availableAmenities.length?<div className={`mt-2 grid gap-2 rounded-xl border p-2 sm:grid-cols-2 ${showErrors&&!option.access.some(item=>availableAmenities.includes(item))?"border-red-500":"border-zinc-200 dark:border-white/10"}`}>{availableAmenities.map(amenity=>{const checked=option.access.includes(amenity);return <label key={amenity} className={`flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2.5 text-sm transition ${checked?"border-[#22c55e] bg-[#22c55e]/10":"border-zinc-200 bg-white dark:border-white/10 dark:bg-white/5"}`}><input type="checkbox" checked={checked} onChange={()=>update(index,{access:checked?option.access.filter(item=>item!==amenity):[...option.access,amenity]})} className="h-4 w-4 accent-[#22c55e]"/><span>{amenity}</span></label>})}</div>:<p className={`mt-2 rounded-xl border p-3 text-sm ${showErrors?"border-red-500 text-red-500":"border-zinc-200 text-zinc-500 dark:border-white/10"}`}>Select amenities under Facility details before choosing membership access.</p>}</fieldset>
        <label className={`${label} sm:col-span-2`}>Membership purchase URL<input type="text" inputMode="url" className={fieldClass(index===0&&!option.purchaseUrl)} value={index>0&&!option.purchaseUrl ? options[0]?.purchaseUrl ?? "" : option.purchaseUrl} onChange={event => update(index, { purchaseUrl: event.target.value })} placeholder="gym.com/memberships" /></label>
        <label className={`${label} sm:col-span-2`}>Additional notes <span className="text-xs font-normal text-zinc-400">Optional</span><textarea rows={3} className={input} value={option.notes} onChange={event => update(index, { notes: event.target.value })} /></label>
      </div>
    </article>)}
    <button type="button" onClick={() => onChange([...options, { ...emptyMembershipOption(), purchaseUrl: options[0]?.purchaseUrl ?? "" }])} className="inline-flex items-center gap-2 rounded-xl border border-[#22c55e] bg-[#22c55e] px-4 py-2.5 text-sm font-black text-black transition hover:bg-zinc-50 hover:text-[#22c55e] dark:hover:bg-neutral-950"><Plus size={17}/>Add membership option</button>
  </div>;
}
